# Generated by Django 5.2 on 2025-05-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='mark_price',
        ),
        migrations.RemoveField(
            model_name='position',
            name='session_avg_price',
        ),
        migrations.AddField(
            model_name='position',
            name='type_trailing_stop',
            field=models.CharField(
                blank=True,
                choices=[('FIXED', 'Фиксированный'), ('PERCENTAGE', 'Процентный')],
                max_length=20,
                null=True,
                verbose_name='Тип трейлинг-стопа',
            ),
        ),
    ]
