# Generated by Django 5.2 on 2025-05-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_position_mark_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='position_value',
        ),
    ]
