# Generated by Django 5.2 on 2025-05-10 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_position_position_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                (
                    'chart_link',
                    models.URLField(
                        blank=True,
                        help_text='Ссылка на график, к которому относится комментарий',
                        null=True,
                        verbose_name='Ссылка на график',
                    ),
                ),
                ('comment', models.TextField(max_length=2048, verbose_name='Комментарий')),
                (
                    'position',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='accounting.position',
                        verbose_name='Позиция',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Комментарий к позиции',
                'verbose_name_plural': 'Комментарии к позициям',
                'ordering': ['-created_at'],
            },
        ),
    ]
