# Generated by Django 5.2 on 2025-05-04 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FinancialAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('ticker', models.CharField(db_index=True, max_length=50, verbose_name='Тикер')),
                (
                    'type',
                    models.CharField(
                        choices=[('ST', 'Акция'), ('CR', 'Валюта'), ('CC', 'Криптовалюта')],
                        max_length=2,
                        verbose_name='Тип актива',
                    ),
                ),
                (
                    'market',
                    models.CharField(
                        choices=[
                            ('SP', 'Спот'),
                            ('FU', 'Фьючерсы'),
                            ('OP', 'Опционы'),
                            ('MA', 'Маржинальная торговля'),
                        ],
                        max_length=2,
                        verbose_name='Рынок',
                    ),
                ),
                (
                    'exchange',
                    models.CharField(
                        choices=[('ByBit', 'ByBit'), ('KuCoin', 'KuCoin')], max_length=50, verbose_name='Биржа'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Финансовый актив',
                'verbose_name_plural': 'Финансовые активы',
                'constraints': [
                    models.UniqueConstraint(fields=('ticker', 'type', 'market', 'exchange'), name='unique_asset')
                ],
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('traded', models.BooleanField(default=True, verbose_name='Торгуется')),
                (
                    'base_asset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='base_trading_pairs',
                        to='accounting.financialasset',
                        verbose_name='Базовый актив',
                    ),
                ),
                (
                    'quote_asset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='quote_trading_pairs',
                        to='accounting.financialasset',
                        verbose_name='Котируемый актив',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Торговая пара',
                'verbose_name_plural': 'Торговые пары',
                'constraints': [models.UniqueConstraint(fields=('base_asset', 'quote_asset'), name='unique_pair')],
            },
        ),
    ]
