# Generated by Django 5.2 on 2025-05-04 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                (
                    'trading_pair',
                    models.CharField(
                        help_text='Торговая пара (например, BTCUSDT)', max_length=20, verbose_name='Торговая пара'
                    ),
                ),
                (
                    'side',
                    models.CharField(
                        choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10, verbose_name='Направление'
                    ),
                ),
                ('size', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Размер')),
                (
                    'position_value',
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Стоимость позиции'),
                ),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Цена входа')),
                (
                    'mark_price',
                    models.DecimalField(
                        decimal_places=8,
                        help_text='Текущая рыночная цена, используемая для оценки позиции',
                        max_digits=20,
                        verbose_name='Маркированная цена',
                    ),
                ),
                ('leverage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кредитное плечо')),
                (
                    'position_im',
                    models.DecimalField(
                        decimal_places=8,
                        help_text='Начальное требование по марже для открытия позиции',
                        max_digits=20,
                        verbose_name='Начальная маржа',
                    ),
                ),
                (
                    'position_mm',
                    models.DecimalField(
                        decimal_places=8,
                        help_text='Минимальная маржа, необходимая для поддержания открытой позиции',
                        max_digits=20,
                        verbose_name='Маржа поддержки',
                    ),
                ),
                (
                    'liq_price',
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text='Цена, при достижении которой позиция будет ликвидирована системой',
                        max_digits=20,
                        null=True,
                        verbose_name='Цена ликвидации',
                    ),
                ),
                (
                    'take_profit',
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Тейк-профит'
                    ),
                ),
                (
                    'stop_loss',
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Стоп-лосс'
                    ),
                ),
                (
                    'trailing_stop',
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Трейлинг-стоп'
                    ),
                ),
                (
                    'unrealised_pnl',
                    models.DecimalField(
                        decimal_places=8,
                        help_text='Текущая нереализованная (бумажная) прибыль или убыток по позиции',
                        max_digits=20,
                        verbose_name='Нереализованный PnL',
                    ),
                ),
                (
                    'cur_realised_pnl',
                    models.DecimalField(
                        decimal_places=8,
                        help_text='Прибыль или убыток, реализованные с момента открытия позиции',
                        max_digits=20,
                        verbose_name='Текущий реализованный PnL',
                    ),
                ),
                (
                    'cum_realised_pnl',
                    models.DecimalField(
                        decimal_places=8,
                        help_text='Кумулятивная сумма реализованной прибыли или убытка с момента открытия позиции',
                        max_digits=20,
                        verbose_name='Накопл. реализ. PnL',
                    ),
                ),
                (
                    'session_avg_price',
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text='Средняя цена входа за текущую торговую сессию',
                        max_digits=20,
                        null=True,
                        verbose_name='Ср. цена сессии',
                    ),
                ),
                ('data_created_time', models.DateTimeField(verbose_name='Время создания позиции')),
                ('data_updated_time', models.DateTimeField(verbose_name='Время обновления позиции')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='positions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
    ]
